name: CI

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  CI: true
  NODE_VERSION: 16

jobs:
  sls-mentor:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: action
        uses: ./.github/actions/sls-mentor-action-test
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
