name: Release

on:
  # This job runs when a new release is published
  release:
    types: [published]

env:
  CI: true
  NODE_VERSION: 16

jobs:
  release:
    name: Release to NPM
    defaults:
      run:
        working-directory: ./packages/cli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
      - name: Install & cache node dependencies
        uses: ./.github/actions/install
      # Store the name of the release
      # See https://stackoverflow.com/questions/58177786/get-the-current-pushed-tag-in-github-actions

      - name: Copy paste root README to @sls-mentor/sls-mentor
        run: cp ../../README.md ./README.md

      - name: pnpm run build
        run: pnpm run build

      - run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - run: pnpm version $RELEASE_VERSION --no-git-tag-version
      - run: echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" >> .npmrc && pnpm i && pnpm publish --access public --no-git-checks && rm .npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
